# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9135c668d263ef1aead0d20914d3ddc6c7802b8d483e8fb5bcd09a532b13da154e29cfeb4282c2fa2c8444eaff7d18e75f49026b00590b61e621e934df4b7eb9

test:
  secret_key_base: 4637408a7fe8a4fe73b845489b0baa22e512fccee55cef5739cc23c2eed57c3daf650c4cdf7764bee545871c376fd86e3f210c3595fcfcfb7ff790d2350f00ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
